version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_HUGGING_FACE_API_KEY=${NEXT_PUBLIC_HUGGING_FACE_API_KEY}
        - NEXT_PUBLIC_HUGGING_FACE_MODEL_NAME=${NEXT_PUBLIC_HUGGING_FACE_MODEL_NAME}
        - MUSICMATE_API_KEY=${MUSICMATE_API_KEY}
        - RECIPE_API_KEY=${RECIPE_API_KEY}
        - CHATBOT_BASE_URL=${CHATBOT_BASE_URL}
        - FORUM_API_URL=${FORUM_API_URL}

    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_HUGGING_FACE_API_KEY=${NEXT_PUBLIC_HUGGING_FACE_API_KEY}
      - NEXT_PUBLIC_HUGGING_FACE_MODEL_NAME=${NEXT_PUBLIC_HUGGING_FACE_MODEL_NAME}
      - MUSICMATE_API_KEY=${MUSICMATE_API_KEY}
      - RECIPE_API_KEY=${RECIPE_API_KEY}
      - CHATBOT_BASE_URL=${CHATBOT_BASE_URL}
      - FORUM_API_URL=${FORUM_API_URL}